 name: Deploy to Github Pages
  
  
 on:
   push:
     branches:
       - main
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: test
         run: |
         echo test checkout action,
         ls
